---
# tasks file for ansible-role-mongodb

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ mongodb_log_dir }}"
    mode: 0755
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    state: directory
  notify: Restart mongodb

- name: Create db directory
  file:
    path: "{{ mongodb_db_dir }}"
    mode: 0755
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    state: directory
  notify: Restart mongodb

- name: Create mongodb.conf
  template:
    src: mongodb.conf.j2
    dest: "{{ mongodb_conf_file }}"
    validate: echo %s
  notify: Restart mongodb

- name: Start mongodb
  service:
    name: "{{ mongodb_service }}"
    enabled: true
    state: started
